mysql_root_password: htrix
mysql_databases:
  - name: notes
    encoding: latin1
    collation: latin1_general_ci
mysql_users:
  - name: notesapp
    host: "%"
    password: htrix
    priv: "notes.*:ALL"