# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "jenkins"
  config.vm.network 'forwarded_port', guest: 8080, host: 8080, hostip: '127.0.0.1'
  config.vm.network 'forwarded_port', guest: 8091, host: 8091, hostip: '127.0.0.1'
  config.vm.network 'private_network', ip: "192.168.56.5"
  config.vm.provision 'shell', path: 'provision.sh'
  config.vm.provider 'virtualbox' do |v|
    v.memory = 2048
  end  
end


# SET VAGRANT_PREFER_SYSTEM_BIN=0

# https://phoenixnap.com/kb/ssh-permission-denied-publickey -> sudo vi /etc/ssh/sshd_config -> sudo systemctl restart sshd
